config/routes.rb
Rails.application.routes.draw do

  # survey specifics
  resources :demographics
  resources :responses
  resources :questions
  resources :projects
  resources :surveys
  resources :user_responses
  resources :studies
  resources :survey_responses

  get '/submit_survey_responses' => 'surveys#submit_responses', as: :post
  get '/create_survey' => 'surveys#create_survey'
  get 'surveys/:id/survey_respond' => 'surveys#survey_respond'
  get 'projects/:id/survey/new' => 'surveys#new'
  get 'surveys/:id/subjects_survey' => 'surveys#subjects_survey'
  get 'subjects_home' => 'surveys#subjects_home'

  devise_for :users, skip: [:registrations]
  devise_for :researchers
  devise_for :subjects

  # namespace :researcher do
  #   root to: "projects#index"
  # end

  # namespace :subject do
  #   root to: "surveys#subjects_home"
  # end
end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :survey
  has_many :survey_responses
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user! 

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
    @current_question = Question.find(params[:id])
    @current_survey_responses = SurveyResponse.where(:question_id => @current_question.id)
    @current_survey = Survey.find(@current_question.survey_id)
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/editrequire "questions_controller"
  def edit
   # @current_question = Question.find(@question.id)
    
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def question_params
      params[:question]
      #params.require(:project).permit(:title, :description, :user_id)
      params.require(:question).permit(:text,:kind,:survey_id)
    end
    
    def user_only
      unless current_user.user? 
        redirect_to :back, :alert => "You need to be a Researcher to access this page."
      end
    end
end

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	  <%= f.input :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', question_path(@question) %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class = "new">
  <p id="notice"><%= notice %></p>
  <h1><%=@current_question.text%></h1>
  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>
  <%= %>
    <tbody>
    <% bool_1 = 0 %>
    <% bool_2 = 0 %>
      <% @current_survey_responses.each do |response| %>
        <tr>
          <% if @current_question.kind == 0 %>
            <td><%=  "#{response.text}"  %></td>
          <% end %>
          <% if @current_question.kind == 1 %>
            <% if response.bool == 'A' %>
              <% bool_1=bool_1+1 %>
            <%else%>
              <%bool_2=bool_2+1 %>
            <%end%>

          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if @current_question.kind == 1 %>
  <h2><%= @current_question.boolean_option_1+" "+bool_1.to_s %></h2>
  <h2><%= @current_question.boolean_option_2+" "+bool_2.to_s %></h2>
  <%end%>
  <%= link_to 'Edit', edit_question_path(@question) %> |
  <%= link_to 'Back', survey_path(@current_survey) %>
</div>