config/routes.rb
Rails.application.routes.draw do

  # survey specifics
  resources :demographics
  resources :responses
  resources :questions
  resources :projects
  resources :surveys
  resources :user_responses
  resources :studies
  resources :survey_responses

  get '/submit_survey_responses' => 'surveys#submit_responses', as: :post
  get '/create_survey' => 'surveys#create_survey'
  get 'surveys/:id/survey_respond' => 'surveys#survey_respond'
  get 'projects/:id/survey/new' => 'surveys#new'
  get 'surveys/:id/subjects_survey' => 'surveys#subjects_survey'
  get 'subjects_home' => 'surveys#subjects_home'

  devise_for :users, skip: [:registrations]
  devise_for :researchers
  devise_for :subjects

  # namespace :researcher do
  #   root to: "projects#index"
  # end

  # namespace :subject do
  #   root to: "surveys#subjects_home"
  # end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  has_many :surveys

  def self.to_csv(options = {})
    CSV.generate(Hash.new) do |csv|
      csv << ['Project title', 'Survey Title', 'Question', 'Response']

      all.each do |project|
        surveys = Survey.where(projects_id: project.id)
        surveys.each do |survey|
          questions = Question.where(survey_id: survey.id)
          questions.each do |question|
            #question.type 0 is text, and 1 is T/F
            if question.kind == 0
              responses = SurveyResponse.where(question_id: question.id)
              responses.each do |response|
                d = [project.title, survey.name, question.text, response.text]
                csv << d
              end

            # made some changes below for True and False questions. We can't use response.bool
            # since that will give us an A or B (True or False) statement directly from the db.
            # instead, we'd rather have the actual question option (so if they wanted yes/no,
            # true/false, higher/lower, etc) response!
            else question.kind == 1          
              responses = SurveyResponse.where(question_id: question.id)
              responses.each do |response|
                if response.bool == "A"
                  d = [project.title, survey.name, question.text, question.boolean_option_1]
                  csv << d
                end
                if response.bool == "B"
                  d = [project.title, survey.name, question.text, question.boolean_option_2]
                  csv << d
                end
              end
            end


          end
        end
      end
    end
  end
end

app/controllers/projects_controller.rb
require "csv"

class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :researcher?
  # GET /projects
  def index
    @projects = Project.where(:user_id => current_researcher.id)

    respond_to do |format|
      format.html
      format.csv { send_data @projects.to_csv }
    end
  end

  # GET /projects/1
  def show
    @current_project = Project.find(params[:id])
    @current_surveys = Survey.where(projects_id: @current_project.id)
  end

  # GET /projects/new
  def new
    @project = Project.new
    @user_id = current_researcher.id
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  def researcher_only
    unless current_researcher.researcher?
      redirect_to :back,
                  alert: 'You need to be a Researcher to access this page.'
    end
  end

  # Only allow a trusted parameter "white list" through.
  def project_params
    # params[:project]
    params.require(:project).permit(:title, :description, :user_id)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => "#{@user_id}" } %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class = "list-view">
  <p id="notice"><%= notice %></p>
  <% if @projects.length > 0 %>
    <h1>Listing Projects</h1>

    <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><div class="data-listing"><%= link_to "#{project.title}", project %></td></div>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <!--
            <td><%= link_to 'Download', projects_path(format: "csv") %></td>
            -->
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="body-text">
      <p>
      Download your responses!
      </p>
    </div>

    <button><%= link_to 'Download', projects_path(format: "csv") %></button>

    <div class="body-text">
      <p>
      Got a new idea for a project? Just press the button below!
      </p>
    </div>

    <button><%=link_to 'New Project', new_project_path%></button>

  <% else %>
    <h1>
      We see that you havn't created any projects!
    </h1>
    <p>
      A project can have multiple surveys. Think of them like folders to hold your related surveys.
    </p>
    <section class = 'options'>
      <button><%=link_to 'Create a New Project', new_project_path%></button>
    </section>
  <% end %>
</div>

app/views/projects/new.html.erb
<section class = "new-project">
  <h1>New Project</h1>

  <%= render 'form' %>

  <%= link_to 'Back', projects_path %>
</section>

app/views/projects/show.html.erb
<div class = "list-view">

  <p id="notice"><%= notice %></p>

  <p><h2><%= @current_project.title %></h2></p>
  <p><h4><%= @current_project.description %></h4></p>
  <button><%= link_to 'New Survey', "#{@current_project.id}/survey/new"%></button>

  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @current_surveys.each do |survey| %>
        <tr>
          <td><%= link_to "#{survey.name}" , survey %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <hr>
  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', projects_path %> |
  <%= link_to('Logout', destroy_researcher_session_path, :method => :delete) %>
  <%# link_to 'New', new_survey_path %>

</div>