config/routes.rb
Rails.application.routes.draw do

  # survey specifics
  resources :demographics
  resources :responses
  resources :questions
  resources :projects
  resources :surveys
  resources :user_responses
  resources :studies
  resources :survey_responses

  get '/submit_survey_responses' => 'surveys#submit_responses', as: :post
  get '/create_survey' => 'surveys#create_survey'
  get 'surveys/:id/survey_respond' => 'surveys#survey_respond'
  get 'projects/:id/survey/new' => 'surveys#new'
  get 'surveys/:id/subjects_survey' => 'surveys#subjects_survey'
  get 'subjects_home' => 'surveys#subjects_home'

  devise_for :users, skip: [:registrations]
  devise_for :researchers
  devise_for :subjects

  # namespace :researcher do
  #   root to: "projects#index"
  # end

  # namespace :subject do
  #   root to: "surveys#subjects_home"
  # end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :project
  has_many :questions
  validates :name, presence: true
end

app/controllers/surveys_controller.rb
# Access surveys
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show,
                                    :edit,
                                    :update,
                                    :destroy]

  before_action :researcher?, except: [:subjects_home,
                                       :subjects_survey,
                                       :submit_responses]

  before_filter :subject?, only: [:subjects_home]

  # GET /surveys
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  def show
    @current_survey = Survey.find(params[:id])
    @current_project = Project.find(@current_survey.projects_id)
    @current_questions = Question.where(survey_id: @current_survey.id)
    @demo_gender = @current_survey.gender
    @demo_min_age = @current_survey.min_age
    @demo_max_age = @current_survey.max_age
    @demo_education = @current_survey.education_level
    @demo_nationality = @current_survey.nationality
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @project_id = params[:id]
    @current_projects = Project.where(user_id: current_researcher.id)
  end

  # GET /surveys/1/edit
  def edit
    @current_survey = Survey.find(params[:id])
    @project_id = params[:id]
  end

  def survey_respond
    @current_survey = Survey.find(params[:id])
    @current_questions = Question.where(survey_id: @current_survey.id)
  end

  def submit_responses
    text_responses = params['text']

    SurveyResponse.add_responses_text(text_responses, 'text')
    bool_ticker = 0
    until params["bool#{bool_ticker}"].nil?

      bool_ans =  params["bool#{bool_ticker}"]
      bool_ans = bool_ans[0]
      bool_ticker += 1
      SurveyResponse.create(bool: bool_ans[0], question_id: bool_ans[1..-1])
    end
  end

  def subjects_survey
    @survey_id = params[:id]
    @current_survey = Survey.find(params[:id])
    @current_questions = Question.where(survey_id: @current_survey.id)
  end

  # POST /surveys

  def create
    @survey = Survey.new(name: params["survey"]["name"],projects_id: params["survey"]["projects_id"],
                          min_age: params["survey"]["min_age"], max_age: params["survey"]["max_age"],
                            gender: params["gender"],education_level: params["education_level"],
                            nationality: params["nationality"])
    # will need more catagories for hash searches as include more questions
    if @survey.save
      redirect_to @survey, notice: 'survey was successfully created.'
    else
      render :new
    end
  end

  def subjects_home
   @can_see = visible_demo_button?
   @subject_demographic = Demographic.where(user_id: current_subject.id)
   all_surveys = Survey.all
   if(@subject_demographic.length > 0 )
     @subject_demographic.each do |d|
       @valid_surveys = Survey.where("((gender = ? OR gender = ? ) AND (education_level = ? OR education_level = ?)) AND (nationality = ? OR nationality = ?)",d.gender, 'Any',d.education,'Any',d.nationality,'Any')
     end
   end
   #puts "ddddddddd"
   #puts @valid_surveys.length
  end

  def visible_demo_button?
     
    made_demo = Demographic.where(user_id: current_subject.id)
    if made_demo.length >0
      can_see = false
    else
      can_see = true
    end
  end

  def create_survey
    puts "****************** #{params.inspect} *****************"
        @survey = Survey.new(name: params["survey"]["name"],projects_id: params["survey"]["projects_id"],
                          min_age: params["survey"]["min_age"], max_age: params["survey"]["max_age"],
                            gender: params["gender"],education_level: params["education_level"],
                            nationality: params["nationality"])

    text_questions = params['text']
    bool_questions = params['bool_text']
    bool_choice1 = params['bool_choice1']
    bool_choice2 = params['bool_choice2']
    if @survey.save
      text_questions.each do |t|
        Question.create(text: t, kind: 0, survey_id: @survey.id)
      end

      if bool_questions.length > 1

        # Booleans!
        (1..bool_questions.length - 1).each do |i|
          Question.create(text: bool_questions[i],
                          kind: 1,
                          boolean_option_1: bool_choice1[i],
                          boolean_option_2: bool_choice2[i],
                          survey_id: @survey.id)
        end
        
      end

      redirect_to @survey, notice: 'Survey was successfully created.'
    else
      render :new
      puts 'fail'
    end
  end

  # PATCH/PUT /surveys/1
  def update
    if @survey.update(survey_params)
      redirect_to @survey, notice: 'Survey was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /surveys/1
  def destroy
    @survey.destroy
    redirect_to surveys_url, notice: 'Survey was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_survey
    @survey = Survey.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def survey_params
    params.require(:survey).permit(:name, :text, :projects_id, :gender, :min_age, :max_age, :education_level, :nationality)
  end

  

  # def get_signed_in
  #   @signed_in = signed_in
  # end

end

app/views/surveys/_form.html.erb
<%= simple_form_for(@survey, :url => "/create_survey",:html => {:method => :get}) do |f| %>

  <div class="form-inputs">
	  <p>Survey Name</p>
    <%= f.text_field :name %>
  </div>

  <div class="input_fields_wrap sub-section">
  <h4>Questions</h4>
  	 <p>Text Question:<input type="text" name="text[]"></p>
  	 <div><input style="display:none;" type="text" name="bool_text[]"></div>
  	 <div><input style="display:none;" type="text" name="bool_choice1[]"></div>
  	 <div><input style="display:none;" type="text" name="bool_choice2[]"></div>
  	 <div><input style="display:none;" type="text" name="range_text[]"></div>
  	 <div><input style="display:none;" type="text" name="radio_choice1[]"></div>
  	 <div><input style="display:none;" type="text" name="radio_choice2[]"></div>
  	 <div><input style="display:none;" type="text" name="radio_choice3[]"></div>
  	 <div><input style="display:none;" type="text" name="radio_choice4[]"></div>
  	 <div><input style="display:none;" type="text" name="radio_choice5[]"></div>
  </div>

  <div class = "options">
    <%= f.input :projects_id,:as => :hidden,  :input_html => { :value => "#{@project_id}" } %>
    <button class="add_field_button">New Text</button>
    <button class="add_field_button_bool">New True/False </button>
    <button> New Multiple Choice </button>
    <button> New Range </button>
    <button> New Ordinal List</button>
  </div>

  <div class = "sub-section">
    <h2>Now, select what kind of people can respond.</h2>
    <%= f.label "Gender:"%>
    <%= select_tag :gender, options_for_select(r_gender) %>
    <%= f.input :min_age %>
    <%= f.input :max_age %>
    <%= f.label "Education Level:"%>
    <%= select_tag :education_level, options_for_select(r_education) %>
    <%= f.label "Nationality:"%>
    <%= select_tag :nationality, options_for_select(r_nations)%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save this survey!' %>
  </div>

<% end %>

<script type='text/javascript'>
var counter=0
	$(".add_field_button").on("click",function(e){
		e.preventDefault();
		$(".input_fields_wrap").append("<div>Text Question:<input type='text' name='text[]'/><a href='#' class='remove_field'>Remove</a></div>");
	});
	$(".add_field_button_bool").on("click", function(e){
		e.preventDefault();
		$(".input_fields_wrap").append("<div>True/False Prompt <input type='text' name='bool_text[]' />Choice 1<input type='text' name='bool_choice1[]' />Choice 2<input type='text' name='bool_choice2[]' /><a href='#' class='remove_field'>Remove</a></div>");
	});

 </script>

app/views/surveys/create_survey.html.erb
Survey created!

<br>
<%= link_to 'Return to Survey', surveys_path%>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', survey_path(@current_survey) %>

app/views/surveys/index.html.erb
<section class = "list-view">
  <p id="notice"><%= notice %></p>

  <h1>All Surveys</h1>

  <% if researcher_signed_in?  %>
    <button><%= link_to 'New Survey', new_survey_path %></button>
  <%end%>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Question</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @surveys.each do |survey| %>
        <tr>
          <td><%= survey.name %></td>

          <td><%= link_to 'Show', survey %></td>
          <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
          <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if subject_signed_in? %>
  <% end %>
</section>

app/views/surveys/new.html.erb
<div class = "new">
  <h1>New Survey</h1>

  <%= render 'form' %>
</div>

app/views/surveys/show.html.erb
<div class = "new">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Survey Name:</strong>
    <%= @survey.name %>
  </p>
  <p>
	  <strong>Demographic Information:</strong>
	  <br>Gender: <%= @demo_gender%></br>
	  <br>Age range: <%= @demo_min_age%> - <%= @demo_max_age%></br>
	  <br>Nationality: <%= @demo_nationality%></br>
    <br>Education: <%= @demo_education%></br>
  </p>

  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @current_questions.each do |question| %>
        <tr>
          <td><%= link_to "#{question.text}" , question %></td>
        </tr>
      <% end %>
    </tbody>
  </table>



  <% if researcher_signed_in?  %>
  <%= link_to 'Edit', edit_survey_path(@survey) %> |
  <%= link_to 'Back', project_path(@current_project) %> |
  <%= link_to('Logout', destroy_researcher_session_path, :method => :delete) %>
  <%end%>

  <% if subject_signed_in? %>
  <%= link_to 'Respond', "/surveys/#{@survey.id}/survey_respond" %> ||
  <%= link_to 'Back', "/subjects" %>
  <br>
  <%= link_to('Logout', destroy_subject_session_path, :method => :delete) %>
  <%end%>

</div>

app/views/surveys/subjects_home.html.erb
<div class = "list-view">
  <p id="notice"><%= notice %></p>

  <h1>Listing Surveys</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
    <% if @valid_surveys != nil %>
      <% @valid_surveys.each do |survey| %>
        <tr>
          <td><%= link_to "#{survey.name}", "surveys/#{survey.id}/subjects_survey" %></td>
        </tr>
      <% end %>
      <% else %>
      <h2> We see you haven't set any demographic info! Enter it below so we can match you with surveys relivant to you! </h2>
      <% end %>
    </tbody>
  </table>
  <% if @can_see %>
    <button><%= link_to "Set Demographic", new_demographic_path %></button>
  <% end %>
</div>

app/views/surveys/subjects_survey.html.erb
<h1><%= @current_survey.name %></h1>
<%= form_tag("/submit_survey_responses", method: "get") do %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
<% radio_counter = 0 %>
  <tbody>
    <% @current_questions.each do |question| %>
      <tr>
	        <%if question.kind == 0 %>  
	        	<%= label_tag(:q, "#{question.text}") %>
	  			<%= text_field_tag('text[]'+ question.id.to_s) %>
			<%end%>
			<%if question.kind == 1 %>  
			    <%= label_tag(:q, "#{question.text}") %>
	        	<%= label_tag("#{question.boolean_option_1}") %>	
	        	<%= radio_button_tag("bool#{radio_counter}[]", "A"+ question.id.to_s) %>
	  			<%= label_tag("#{question.boolean_option_2}") %>
	  			<%= radio_button_tag("bool#{radio_counter}[]", "B"+ question.id.to_s) %>
	  			<% radio_counter = radio_counter+1 %>
			<%end%><!--need one for multi choice also -->
      </tr>
    <% end %>

  </tbody>
</table>
<%= submit_tag("Submit Responses") %>
<br>
<%= link_to 'Back', "/subjects" %>
<br>
<%= link_to('Logout', destroy_subject_session_path, :method => :delete) %>
<%end%>

app/views/surveys/submit_responses.html.erb
<h1> Responses Submitted! </h1>
<a href="/subjects_home">Home</a>

app/views/surveys/survey_respond.html.erb
<h1><%= @current_survey.name %></h1>
<%= form_tag("/submit_survey_responses", method: "get") do %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @current_questions.each do |question| %>
      <tr>
	        <%if question.kind == 0 %>  
	        	<%= label_tag(:q, "#{question.text}") %>
	  			<%= text_field_tag('text[]'+ question.id.to_s) %>
			<%end%>
			<%if question.kind == 1 %>  
			    <%= label_tag(:q, "#{question.text}") %>
	        	<%= radio_button_tag(:bool, "A"+ question.id.to_s) %><!-- for second param the bool options it must be -->
	  			<%= label_tag("A") %> <!--same here -->
	  			<%= radio_button_tag(:bool, "B"+ question.id.to_s) %>
	  			<%= label_tag("B") %> 
			<%end%><!--need one for multi choice also -->
      </tr>
    <% end %>

  </tbody>
</table>
<%= submit_tag("Submit Responses") %>
<br>
<%= link_to 'Back', "/subjects" %>
<br>
<%= link_to('Logout', destroy_subject_session_path, :method => :delete) %>
<%end%>