config/routes.rb
Rails.application.routes.draw do

  # survey specifics
  resources :demographics
  resources :responses
  resources :questions
  resources :projects
  resources :surveys
  resources :user_responses
  resources :studies
  resources :survey_responses

  get '/submit_survey_responses' => 'surveys#submit_responses', as: :post
  get '/create_survey' => 'surveys#create_survey'
  get 'surveys/:id/survey_respond' => 'surveys#survey_respond'
  get 'projects/:id/survey/new' => 'surveys#new'
  get 'surveys/:id/subjects_survey' => 'surveys#subjects_survey'
  get 'subjects_home' => 'surveys#subjects_home'

  devise_for :users, skip: [:registrations]
  devise_for :researchers
  devise_for :subjects

  # namespace :researcher do
  #   root to: "projects#index"
  # end

  # namespace :subject do
  #   root to: "surveys#subjects_home"
  # end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  <script src="/assets/jquery-1.11.2.min.js" type="text/javascript"></script>
</head>
<body class="<%= body_class %>">
  <header class="navigation" role="banner">
    <div class="navigation-wrapper">
      <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
      <nav role="navigation">
        <ul id="js-navigation-menu" class="navigation-menu show">
          <li class="nav-link"><a href="/">Surveyor</a></li>
          <li class="nav-link"><a href="javascript:void(0)">About</a></li>
          <li class="nav-link"><a href="javascript:void(0)">Contact</a></li>

          <% if current_researcher %>
            <li class="nav-link"><%= link_to('Projects Dashboard', projects_path)%></li>
            <li class="nav-link"><%= link_to('Logout', destroy_researcher_session_path, :method => :delete) %></li>
          <% end %>

          <% if current_subject %>
            <li class="nav-link"><%= link_to('Dashboard', subjects_home_path)%></li>
            <li class="nav-link"><%= link_to('Logout', destroy_subject_session_path, :method => :delete) %></li>
          <% end %>
        </ul>
      </nav>
      <div class="navigation-tools">
        <div class="search-bar">
          <form role="search">
            <input type="search" placeholder="Enter Search" />
            <button type="submit">
              <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
            </button>
          </form>
        </div>

        <% if !(current_subject || current_researcher) %>
          <a href="/login" class="sign-up">Sign Up</a>
        <% end %>

      </div>
    </div>
  </header>
  <%= render "flashes" -%>
  <div class = "container">
    <%= yield %>
  </div>
  <%= render "javascript" %>

  <footer class="footer" role="contentinfo">
  <div class="footer-links">
    <ul>
      <li><h3>Content</h3></li>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
    </ul>
    <ul>
      <li><h3>Follow Us</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">Twitter</a></li>
    </ul>
    <ul>
      <li><h3>Legal</h3></li>
      <li><a href="javascript:void(0)">Terms and Conditions</a></li>
      <li><a href="javascript:void(0)">Privacy Policy</a></li>
    </ul>
  </div>

  <hr>

  <p>&copy; 2015 Surveyor Team</p>
</footer>
</body>
</html>